version: '3.8'
services:
  snippet:
    build: ./
    command: /app/cmd/web/main
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=postgres

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=snippet
volumes:
  pgdata:
